zzf/add op bernoulli
DeepLink-org/DIOPI pull request #367
Opened 2023-08-30 09:48 UTC by Zhang-ze-feng

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation and Context
add op bernoulli

## Description

## Use cases (Optional)

## BC-breaking (Optional)

## Checklist
**Before PR**:

- [x] I have read and followed the workflow indicated in the [Contributors.md](https://github.com/DeepLink-org/DIOPI/blob/main/Contributors.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [Contributors.md](https://github.com/DeepLink-org/DIOPI/blob/main/Contributors.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] CLA has been signed and all committers have signed the CLA in this PR.

2023-08-30 10:09 UTC, yangbofun commented on impl/camb/functions/bernoulli.cpp
> +DIOPI_API diopiError_t diopiBernoulli(diopiContextHandle_t ctx, diopiTensorHandle_t out, diopiConstTensorHandle_t input, diopiGeneratorHandle_t generator) {
generator，没有使用。

2023-08-30 13:14 UTC, yangbofun commented on impl/camb/functions/bernoulli.cpp
> +    DiopiTensor outTemp = requiresTensor(ctx, inputTensor.shape(), inputTensor.dtype());
可以删除这句话，不用使用outTmp。直接使用out， 然后diopiLt那里使用diopiLtInp函数。

2023-08-30 13:14 UTC, yangbofun commented on impl/camb/functions/bernoulli.cpp
> +    DiopiTensor outTemp = requiresTensor(ctx, outTensor.shape(), outTensor.dtype());
同上，可以删除。下面的diopiLtScalar，可以调用diopiLtInpScalar.

2023-08-31 03:00 UTC, yangbofun commented on impl/camb/functions/bernoulli.cpp
> +    DIOPI_CALLCNNL(cnnlRandGenerateUniform(handle, cnnlGenerator, dtype, statePtr, inputTensor.numel(), 0, 1, outputTensor.data()));
inputTensor和outputTensor上的dtype的不一样的话，计算结果会出错。

2023-08-31 03:36 UTC, caikun-pjlab requested changes

2023-08-31 03:36 UTC, caikun-pjlab commented on impl/camb/functions/bernoulli.cpp
> +    DIOPI_CALLCNNL(cnnlRandDestroyGenerator(cnnlGenerator));
参考uniform算子的实现，调用完cnnlRandGenerateUniform算子之后，需要调用diopiGeneratorSetState将state写回到generator中

2023-08-31 03:36 UTC, caikun-pjlab commented on impl/camb/functions/bernoulli.cpp
> +    DIOPI_CALL(diopiLtInpScalar(ctx, out, &scalar));
同上

2023-09-05 05:59 UTC, caikun-pjlab approved these changes

2023-09-06 03:02 UTC, yangbofun approved these changes

2023-09-06 03:02 UTC, merged