Dev for ext
DeepLink-org/DIOPI pull request #469
Opened 2023-10-12 09:43 UTC by wey-code

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation and Context

## Description

## Use cases (Optional)

## BC-breaking (Optional)

## Checklist
**Before PR**:

- [ ] I have read and followed the workflow indicated in the [Contributors.md](https://github.com/DeepLink-org/DIOPI/blob/main/Contributors.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [Contributors.md](https://github.com/DeepLink-org/DIOPI/blob/main/Contributors.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-10-13 08:11 UTC, yangbofun commented on proto/include/diopi/functions_ext.h
> +
写一下接口说明

2023-10-13 08:44 UTC, yangbofun commented
测试，可以写进diopi test. 自定义custom test。

2023-11-02 10:09 UTC, wey-code commented on proto/include/diopi/functions_ext.h
> +
done

2023-11-02 12:26 UTC, yangbofun commented on .github/workflows/main.yml
> +          ${run_test} main.py --mode run_test --fname index_select --four_bytes && ${run_test} main.py --mode run_test --fname arange --four_bytes && ${run_test} main.py --mode run_test --fname rms_n
这里删了吧，不用测，在dyload_test里面已经测了。

2023-11-02 12:40 UTC, yangbofun commented on impl/camb/device_configs.py
> -                    "dtype": [Skip(Dtype.float64), Skip(Dtype.int64), Skip(Dtype.bool)]
这里不用修改。

2023-11-02 12:49 UTC, wey-code commented on .github/workflows/main.yml
> +          ${run_test} main.py --mode run_test --fname index_select --four_bytes && ${run_test} main.py --mode run_test --fname arange --four_bytes && ${run_test} main.py --mode run_test --fname rms_n
done

2023-11-02 12:49 UTC, wey-code commented on impl/camb/device_configs.py
> -                    "dtype": [Skip(Dtype.float64), Skip(Dtype.int64), Skip(Dtype.bool)]
done

2023-11-03 03:12 UTC, lljbash commented on impl/torch/functions_ext/flash-attention/CMakeLists.txt
> +#   PREFIX "")
```suggestion
```

2023-11-03 04:02 UTC, wey-code commented on impl/torch/functions_ext/flash-attention/CMakeLists.txt
> +target_link_libraries(diopi_torch_ext_flash_attn INTERFACE flash_attn_2_cuda.cpython-38-x86_64-linux-gnu)
```suggestion
target_link_libraries(diopi_torch_ext_flash_attn INTERFACE  -Wl,--no-as-needed flash_attn_2_cuda.cpython-38-x86_64-linux-gnu -Wl,--as-needed)
```

2023-11-03 04:02 UTC, wey-code commented on impl/torch/functions_ext/flash-attention/CMakeLists.txt
> +target_link_libraries(diopi_torch_ext_flash_attn INTERFACE flash_attn_2_cuda.cpython-38-x86_64-linux-gnu)
用于解决弱符号链接不上的问题

2023-11-03 04:54 UTC, lljbash commented on impl/torch/CMakeLists.txt
> +
看起来没用到啊

2023-11-03 05:04 UTC, wey-code commented on impl/torch/CMakeLists.txt
> +
这个是最开始想通过架构来判断是否链接flash-attention，后面改了，没删干净

2023-11-03 06:40 UTC, lljbash commented on impl/torch/functions_ext.cpp
> +    std::vector<at::Tensor> result = mha_varlen_bwd(atGrad_out,
输出不需要造，rng state 也不用存，参见上面的写法

2023-11-03 06:40 UTC, lljbash commented on impl/torch/functions_ext.cpp
> +    updateGeneratorStateForMha(ctx, gen, atRngState);
rng state 不用存

2023-11-03 06:41 UTC, lljbash commented on impl/torch/functions_ext.cpp
> +    // impl::aten::updateATen2Tensor(ctx, atOutput, out);
不用的代码去掉

2023-11-03 06:41 UTC, lljbash requested changes

2023-11-03 06:41 UTC, lljbash commented on impl/torch/functions_ext.cpp
> +    impl::aten::updateATen2Tensor(ctx, atOutpaded, out);
这个 size 可以确保一致吗？

2023-11-03 08:40 UTC, lljbash commented on impl/torch/functions_ext.cpp
> +    impl::aten::updateATen2Tensor(ctx, atOutpaded, out);
不能，以后再改

2023-11-03 10:22 UTC, lljbash commented on impl/torch/CMakeLists.txt
> +
删掉了

2023-11-03 10:23 UTC, lljbash approved these changes

2023-11-07 06:54 UTC, yangbofun approved these changes

2023-11-07 06:55 UTC, merged